### ISSUE TITLE
As a user, I want to be able to write comments and leave a rating on a specific bathroom. 

### ISSUE THREAD

**Issue by nicholasruan** [nyu-software-engineering/toilet-finder#10]
- [x] Open location page
- [x] Fill out a form to leave comments and a rate of toilet locations
- [x] See own comment and rate on the location page after submitting form

Estimate of work: Medium

Sprint 4 estimate of work: medium

**Comment by shanyk** [comment]
- [ ] allow user input
- [ ] update database location entry with user review
